# Generated by Django 5.0.7 on 2024-07-31 04:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_usergame'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='user',
        ),
        migrations.AddField(
            model_name='game',
            name='users',
            field=models.ManyToManyField(through='games.UserGame', to=settings.AUTH_USER_MODEL),
        ),
    ]
