# Generated by Django 4.2.14 on 2024-07-31 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_remove_game_user_game_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='total_score',
        ),
    ]
