# Generated by Django 5.0.7 on 2024-08-11 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0004_remove_game_total_score'),
        ('questions', '0005_remove_question_is_correct_question_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='usergame',
            name='answered_questions',
            field=models.ManyToManyField(to='questions.question'),
        ),
    ]
