# Generated by Django 4.2.14 on 2024-08-15 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0006_alter_question_question'),
        ('games', '0005_usergame_answered_questions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usergame',
            name='answered_questions',
            field=models.ManyToManyField(null=True, to='questions.question'),
        ),
    ]
