# Generated by Django 4.2.14 on 2024-08-22 21:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0008_remove_game_users_alter_usergame_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usergame',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_games', to='games.game'),
        ),
    ]
