# Generated by Django 4.2.14 on 2024-07-30 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('options', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='option',
            name='is_correct',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='option',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
