# Generated by Django 5.0.7 on 2024-07-31 04:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('options', '0003_alter_option_is_correct_alter_option_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='option',
            name='score',
        ),
    ]
