# Generated by Django 4.2.14 on 2024-08-15 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('options', '0005_alter_option_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='option',
            name='option',
            field=models.CharField(max_length=500),
        ),
    ]
