# Generated by Django 4.2.14 on 2024-07-30 18:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
        ('questions', '0002_alter_question_is_correct_alter_question_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='games.game'),
        ),
    ]
