# Generated by Django 4.2.14 on 2024-07-30 19:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
        ('questions', '0003_alter_question_game'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='score',
        ),
        migrations.AlterField(
            model_name='question',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.game'),
        ),
    ]
